### PR TITLE
Added Murata

### PR DESCRIPTION
**Pull request by shashank1529**
Hii ,
Please review my PR of Hacktoberfest 2022

### CODE REVIEW

**Comment by mShashank2308** [comment]
The image for the character you have added is not present. Please add the image and commit again.

**Comment by shashank1529** [comment]
I added the image please check

**Comment by mShashank2308** [comment]
The image is not showing. I suggest that you download the image and put it in the images folder and update the path.
This is how your added card looks like: 

mu

**Comment by mShashank2308** [comment]
Please sync your fork and commit again.

**Pull request closed without merging**
